insert into tipos (sigla,rotulo) values ('pla','Placa de video');
insert into tipos (sigla,rotulo) values ('har','Hardware');
insert into tipos (sigla,rotulo) values ('per','Periférico');
insert into tipos (sigla,rotulo) values ('cad','Caddeira');
insert into tipos (sigla,rotulo) values ('mon','Monitor');
insert into tipos (sigla,rotulo) values ('acs','Acessórios');

insert into produtos ( titulo, descricao, resumo, preco, image, destaque, tipos_id) values ( 'Placa Gráfica Nvidia RTX2060', 'As placas gráficas GeForce RTX são equipadas com a arquitetura Turing GPU e a nova plataforma RTX. Isso oferece maior desempenho em comparação com as placas gráficas da geração anterior e traz o poder do traçado de raios em tempo real e da IA ??para os jogos.','KO Ultra Gaming 6GB GDDR6', 2344.99, 'nvidiartx.png', 'sim', 1);
insert into produtos ( titulo, descricao, resumo, preco, image, destaque, tipos_id) values ( 'PLACA DE VIDEO MSI GEFORCE GTX 1650', 'O dissipador de calor extrudado de alumínio maximiza a área de contato direto com a GPU e a memória para transferir o calor com eficiência. Melhora a dissipação de calor ao guiar o fluxo de ar para o PCB através das seções do dissipador de calor.','Esse componente eletrônico processa as informações que chegam ao dispositivo e as transforma em imagens ou vídeos para exibi-las visualmente.', 959.99, 'pvmsi.png', 'sim', 1);
insert into produtos ( titulo, descricao, resumo, preco, image, destaque, tipos_id) values ( 'Cadeira Gamer Craft Preta e Vermelha', 'Se você passa um longo período de tempo sentado na frente do computador sabe o quanto a cadeira influencia no aconchego do seu corpo, não é? E para aprimorar esses momentos, nada melhor do que contar com um móvel como a Cadeira Gamer Craft. Além de estrutura aconchegante, ela também possui apoio para os braços com regulagem, ajuste de altura e rodízios – tudo para se adaptar às suas necessidades.','Para ficar em uma posição ideal, com as pernas bem apoiadas e confortáveis enquanto joga, o sistema de ajuste de altura dessa cadeira é ótimo - ao acionar o dispositivo na base,', 803.58, 'cadeirag.webp', 'sim', 4);
insert into produtos ( titulo, descricao, resumo, preco, image, destaque, tipos_id) values ( 'Cadeira Gamer Ninja Twilight, Preto e Branco', 'Assegurando um produto de qualidade com ajuste de altura.as cadeiras gamer Ninja foram feitas para acompanhar gamers de diversas alturas, além de proporcionar uma postura correta e melhor adaptação do jogador em relação à sua área de trabalho. ','Desenvolvida especialmente para gamers. A Gamer Ninja Twilight foi projetada para você aproveitar o máximo de tempo nas suas jogatinas ou até mesmo em seu trabalho, uma cadeira extremamente confortável e de alta qualidade.', 470.47, 'cadeiranin.png', 'sim', 4);
insert into produtos ( titulo, descricao, resumo, preco, image, destaque, tipos_id) values ( 'Processador AMD Ryzen 5 5600G 3.9GHz (4.4GHz Turbo)', 'O Ryzen 5 5600G conta com 6 núcleos incríveis para quem quer apenas jogar. Os processadores AMD Ryzen série 5000 capacitam a próxima geração de jogos exigentes, proporcionando experiências imersivas únicas e dominando qualquer tarefa multithread como 3D e renderização de vídeo e compilação de software.','Com grande poder de processamento do seu vídeo integrado, vêm as tecnologias de ponta para ​oferecer suporte.', 1045.88, 'amd-5.webp', 'sim', 2);